name: CI Pipeline

on:
  push:
    branches:
      - main

env:
    AWS_REGION: ${{ secrets.AWS_REGION }} #AWS region for ECR
    ECR_REPOSITORY: my-nextjs-app #ECR repository name
    IMAGE_TAG: ${{ github.sha }} #Git SHA

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            # Step 1: checkout the code from Github
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up Node.js ( for next.js build)
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            # Step 3: Install app dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Placceholder for tests ( optional)
            - name: Run tests
              run: npm test || echo "No tests defined"  
              
            # Step 5: Set up Docker Buildx ( for cross-platform builds if needed)
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            #Step 6: Login to Amazon ECR using Github Secrets
            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION}}

            # step7: Build and push Docker image to ECR using Git SHA as tag
            - name: Build and push Docker image
              run: |
                docker build -t 896060361783.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push 896060361783.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

            # step8: tag and push image to ECR using latest tag
            - name: Tag and push image
              run: |
                docker tag 896060361783.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG 896060361783.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:latest
                docker push 896060361783.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:latest


                

          

        
